### ISSUE TITLE
The Vim Fireplace Instrucions Do Not Work

### ISSUE THREAD

**Issue by rhg** [adzerk-oss/boot-cljs-repl#12]
When I type :Piggieback (repl-env) I get a stack trace fragment saying repl-env can't be found.
Passing the fully qualifed repl-env (adzerk.boot-cljs-repl/repl-env) does though.

**Comment by jessesherlock** [comment]
This was working for me earlier today, now I get "No value supplied for key: weasel.repl.websocket.WebsocketEnv@...".

**Comment by jessesherlock** [comment]
Ok, figured it out. Fireplace pushed a change today to conform to piggieback 2.X and the function :Piggieback calls is affected.

**Comment by ethagnawl** [comment]
I'm also seeing the Weasel WebSocket error. Should this issue be raised with vim-fireplace? Does anyone know of a workaround that doesn't involve rolling back vim-fireplace?

**Comment by Deraen** [comment]
Problem is that boot-cljs-repl is using old Piggieback, it's not an issue with vim-fireplace.

**Comment by pkobrien** [comment]
We are now using the newest Piggieback. Can vim-fireplace users try the latest `[adzerk/boot-cljs-repl "0.1.10-SNAPSHOT"]` to see if it works for you?

**Comment by Deraen** [comment]
I've been successfully using boot-cljs-repl with fireplace for some time (occasionally).

**Comment by vushu** [comment]
When following the current instructions for vim fireplace 
then writting `:Piggieback (adzerk.boot-cljs-repl/repl-env) ` in vim
my vim just hangs forever, 
help would be appreciated.
