### ISSUE TITLE
WARNING: org.clojure/tools.nrepl version null is older than required 0.2.10

### ISSUE THREAD

**Issue by pkobrien** [adzerk-oss/boot-cljs-repl#19]
The current 0.1.10-SNAPSHOT produces this warning. Would be nice to have this resolved.

**Comment by zane** [comment]
I ran into this when attempting to run `boot dev` in `boot-cljs-example`. 

As a new boot user I also found the `Connection is null` line being printed by [this call](https://github.com/adzerk-oss/boot-cljs-repl/blob/master/src/adzerk/boot_cljs_repl.clj#L162) disconcerting, but I'm not sure whether that warrants an issue.

**Comment by alandipert** [comment]
Re: `Connection is null`, would `Connection is not yet established` be an improvement?

**Comment by zane** [comment]
Definitely. I read `null` as being indicative of some kind of problem.

**Comment by pkobrien** [comment]
I honestly don't know why the message is there at all and I'm not the author of it so it's hard for me to guess.

**Comment by Deraen** [comment]
This should be resolved with #29 or other PR which implements changes described there.
