### ISSUE TITLE
Improve/standardize method used to compare versions

### ISSUE THREAD

**Issue by pkobrien** [adzerk-oss/boot-cljs-repl#21]
If we need to compare versions of dependencies we should use goog.string.compareVersions.

http://google.github.io/closure-library/api/source/closure/goog/string/string.js.src.html#l1190

**Comment by Deraen** [comment]
We need to compare versions in Clojure and that is a JS library.

**Comment by pkobrien** [comment]
Oops! You are totally correct. That's what I get for spending so much time in cljs-land. There is this library, but I don't know much about it: https://github.com/xsc/version-clj

**Comment by Deraen** [comment]
We should probably think about including these utilities (no matter how they are implemented) in Boot. The tasks shouldn't depend on libraries directly but only through pods and using pods for version comparison would be quite overkill.

**Comment by Deraen** [comment]
Will be unnecessary once we don't automatically add the dependencies but instead check if weasel or piggieback is available and tell user to manually add them to project if they are not.
