### ISSUE TITLE
No REPL connection (fails to set port in time)

### ISSUE THREAD

**Issue by pandeiro** [adzerk-oss/boot-cljs-repl#5]
There is something like a race condition affecting the setting of the port with the `cljs-repl` task:

If no port is specified, the weasel server begins with: `<< started Weasel server on ws://127.0.0.1:0 >>`. (If a port *is* specified, that port shows up in the output.)

And whether or not a port is specified, the generated ClojureScript file used to connect to the REPL server sets an invalid websocket URL: `ws://localhost:null`.

**Comment by pandeiro** [comment]
This appears to be a regression from `0.1.7` to `0.1.8`

**Comment by martinklepsch** [comment]
Confirmed with `0.1.8`.

**Comment by pandeiro** [comment]
Additionally I've noticed that with 0.1.7, the REPL connection is established only if there is no *.cljs.edn build specified (ie, the default 'main.js' is generated). When I do specify builds, the port appears in the server output but the client-side connection function is never called.

(Using boot-cljs from master, not clojars)

**Comment by martinklepsch** [comment]
I guess it must be somewhere in [this commit](https://github.com/adzerk/boot-cljs-repl/commit/7ee48c75d81d31b6463330e3ab473d8523efcbab). 

What's confusing to me is that in the `weasel-connection` function there is a `0` passed as port when none is specified but this has been the case before?!

**Comment by martinklepsch** [comment]
I just tested this with `0.0-2755` which ships some REPL fixes and that seems to fix the problem. I'll PR the boot-cljs repo.

**Comment by martinklepsch** [comment]
Just tested with `0.0-2760` and works fine. Still prints `0` as port:
```
boot.user=> (start-repl)
<< started Weasel server on ws://127.0.0.1:0 >>
Type `:cljs/quit` to stop the ClojureScript REPL
Writing boot_cljs_repl.cljs...
```

**Comment by martinklepsch** [comment]
REPLs still breaking in projects that use CLJSJS-like libraries.

**Comment by pkobrien** [comment]
Is this still an outstanding issue?

**Comment by martinklepsch** [comment]
Probably not. That new weasel stuff worked well when I tested it and this is really old anyways.
