### ISSUE TITLE
Can't start repl anymore

### ISSUE THREAD

**Issue by agzam** [adzerk-oss/boot-cljs-repl#51]
For some reason I can't start cljs-repl anymore.

 whenever I run 
 
     boot repl 
     
     (start-repl)
 
 it keeps saying:

    java.lang.IllegalStateException: Can't change/establish root binding of: *cljs-repl-env* with set

The same thing happening in different projects:

for example this template is failing: `boot -d seancorfield/boot-new new -t oriens -n your-app`
just a few days ago it was working.
I think this is a problem related to piggiback. I still don't know how to fix it

**Comment by agzam** [comment]
I don't get it. I tried removing ~/.boot folder. Re-installing boot. Rimraffing ~/.m2. Still seeing same error. Similar project on lein - cljs-repl works.

**Comment by agzam** [comment]
I was able to successfully bring up cljs-repl only when run the boot repl and in the other terminal window `boot repl --client` and then `(start-repl)`. Using cider-connect for the same thing - just hangs cider-repl.

**Comment by agzam** [comment]
I dunno what it was. Apparently some strange combination of several things getting out of sync - piggiback, weasel and cljs-boot. Finally I have cljs-repl again.

**Comment by alandipert** [comment]
Curious: did changing the version of something cause this problem?

**Comment by agzam** [comment]
@alandipert to be honest I have no idea. Once it worked - I can't repro this anymore.

**Comment by vladanghene** [comment]
the exact thing happened to me today, not working with @agzam solution

**Comment by pdbrown** [comment]
I hit the same exception using `cider-jack-in`, but realized I'd forgotten to add the `:middleware ['cemerick.piggieback/wrap-cljs-repl]` option to the repl I was launching via `cider-boot-parameters`. The middleware establishes a binding scope for `*cljs-repl-env*` (among others), and adding it back fixed the problem.
