### ISSUE TITLE
Help getting connected to a browser repl in cider

### ISSUE THREAD

**Issue by mulchy** [adzerk-oss/boot-cljs-repl#52]
Hi! Thanks for making such awesome libraries :)

This is more of a question than an issue, so I am sorry if this is the wrong forum for it. I am trying to get started using a browser repl in emacs, I have some familiarity using cider on clojure projects, but not much with cljs. I was getting started using this template https://github.com/martinklepsch/tenzing which makes use of the cljs-repl function and many of your other boot tasks. I started by running `boot dev` in my terminal, which as far as I understand starts a web server, a file-watcher, calls cljs-repl, starts the live reloader and builds the project. Then, I ran `cider-connect` in emacs. This works and I get a browser repl after running `(start-repl)` in cider. **However, I can't use any of the built in cider functions to send code to the repl, since it doesn't think I have a cljs repl running**. Some folks in the clojurians slack channel thought I needed to call `cider-jack-in` to start the repl instead. This brings me to my main question,

What is the "right way" to do this? Should I `cider-jack-in` and then follow the steps described here https://github.com/adzerk-oss/boot-cljs-repl#the-cljs-repl-env-task ?

Any advice is greatly appreciated. Thanks!

**Comment by Deraen** [comment]
Both `cider-connect` and `cider-jack-in` ways are documented on readme and both are valid and should work.

**Comment by martinklepsch** [comment]
I'll close this as it's pretty old and OP didn't come back with follow up questions.
