### ISSUE TITLE
start-repl error

### ISSUE THREAD

**Issue by unrealhoang** [adzerk-oss/boot-cljs-repl#8]
I bootstraped my project as close as the boot-cljs-example project as possible, everything works fine, but when i try to run `start-repl` in the `boot repl -c` it throws the error below:

`clojure.lang.ArityException: Wrong number of args (1) passed to: closure/get-upstream-deps*`

My build.boot:
```
(set-env!
  :source-paths   #{"src"}
  :resource-paths #{"html"}
  :dependencies '[[adzerk/boot-cljs      "0.0-2814-3" :scope "test"]
                  [adzerk/boot-cljs-repl "0.1.9"   :scope "test"]
                  [adzerk/boot-reload    "0.2.4" :scope "test"]
                  [pandeiro/boot-http    "0.6.3-SNAPSHOT" :scope "test"] ;; latest release
                  [reagent               "0.5.0-alpha3"]])

(require
  '[adzerk.boot-cljs      :refer [cljs]]
  '[adzerk.boot-cljs-repl :refer [cljs-repl start-repl]]
  '[adzerk.boot-reload    :refer [reload]]
  '[pandeiro.boot-http    :refer [serve]])
```

**Comment by martinklepsch** [comment]
Probably you have a transitive dependency on a version of Clojurescript below `0.0-2814`.
```
boot show -d
```
prints a dependency tree.

Also you should have gotten a warning about this when you started cljs compilation.

**Comment by unrealhoang** [comment]
Oh thanks, I did see the warning. What should I do to resolve it?


—

**Comment by martinklepsch** [comment]
@unrealhoang explicitly specify Clojurescript as a dependency.
```clj
[org.clojure/clojuresript "0.0-2814"]
```
